Configurable style options
Carlgo11/Tron-Clock pull request #1
Opened 2022-10-30 13:28 UTC by ACSimon33

Hi,

I really liked this as a screensaver. I've added some URL parameters to make the font size, letter spacing, and color configurable from the URL. If you want you can integrate that into your repository as well. 

I'm a HTML, CSS and javascript newbie though, so there is probably a better solution to this.

2022-10-30 22:57 UTC, Carlgo11 requested changes
Thanks for the kind words!
I didn't think anyone else would find this interesting :sweat_smile: 

I myself run the screen saver locally so I never thought of offering parameters but I can see how that could be a useful feature to have. I made some minor changes to speed the code up and make it cleaner. Hope that's okay 😉

What do you think about the proposed changes in the README and the changed query parameters?

2022-10-30 22:57 UTC, Carlgo11 commented on README.md
> +```
```suggestion
## Settings
You can modify the style via a query string.
| Name    | Default Value | Units     |
|---------|---------------|-----------|
| size    | 3.25          | em        |
| spacing | 0.16          | em        |
| color   | 96c6a9        | Hex Color |
| bg      | 111           | Hex Color |
```

2022-10-30 23:58 UTC, ACSimon33 commented
Thanks for cleaning up the code. I like the changes (I was sure there had to be a better way than what I found in an 8-year-old StackOverflow post 😅). README looks good as well.

2022-10-31 00:30 UTC, Carlgo11 approved these changes

2022-10-31 00:30 UTC, merged